# `Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.`

In [12]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [13]:
print(list_)

['1', '2', '3', '4', '5']


In [14]:
print(array_list)

['1' '2' '3' '4' '5']


Yes, there is a difference in the data type of the list_ and array_list variables. The list_ variable is a Python list containing string elements, while the array_list variable is a NumPy array created from the list_ with the data type inferred by NumPy.

In [27]:
type(list_)

list

In [25]:
array_list.dtype

dtype('<U1')

In this code, type(list_) will give you the data type of the list_ variable, which is list. And array_list.dtype will give you the data type of the elements within the NumPy array,

# `Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.`

In [44]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


# Print data types of elements in the list
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in the array
print("\nData types of elements in array_list:")
for element in array_list:
    print(element.dtype)


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<U1
<U1
<U1
<U1
<U1


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [39]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [47]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in the list
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in the array
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# `Q4. Write a code to find the following characteristics of variable, num_array:`

## (i) shape

## (ii) size`


In [48]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of the array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of the array
size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


# `Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.`
## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [59]:
import numpy as np
zero_array = np.zeros([3,3])

In [60]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
import numpy as np

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

print("3x3 Array of Zeros:")
print(zeros_array)


3x3 Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# `Q6. Create an identity matrix of shape (5,5) using numpy functions?`
## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [68]:
identity_matrix = np.eye(5)

print("5*5 identity matrix:")

print(identity_matrix)

5*5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
